export enum GenreEnums {
  DRAMA = "Drama",
  COMEDY = "Comedy",
  MYSTERY = "Mystery",
  FANTASY = "Fantasy",
  THRILLER = "Thriller",
  ROMANCE = "Romance",
  HISTORY = "History",
  HORROR = "Horror",
  CRIME = "Crime",
  SCIFI = "Sci-Fi",
  BIOGRAPHY = "Biography",
  ADVENTURE = "Adventure",
  ACTION = "Action",
}
